### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by SacrilAI** [YoFuzzy3/BungeePortals#12]
i created a portal to my pixelmon server, but when i try to cross, bportal says Alreadi conecting to this server, all time say this but never work, in the console of pixelmon appear a message saying disconectin timeout

http://prntscr.com/5qvw30
http://prntscr.com/5qvvvj

how i can fix this?

**Comment by bros1083** [comment]
Maybe the server Address. Look at the IP

**Comment by YoFuzzy3** [comment]
Not a BungeePortals issue.
