### ISSUE TITLE
Big problem..

### ISSUE THREAD

**Issue by DanielTrollz16** [YoFuzzy3/BungeePortals#13]
So basically in the central area of my Hub I had a massive tower with 4 water portals but I changed it so that I could have more portals but after removing all the portals and rebooting my server the portals were invisible and came back so I contacted my server hosters support service and they worked for almost a week with me to try and fix it and it just wouldn't go away, we can remove any other portals fine and the data saves fine but the data just won't save for these specific portals we have tried anything and then they advised us to come here.

What to do?

**Comment by YoFuzzy3** [comment]
Clear the portals.yml file while the server is off, then start over.
