### ISSUE TITLE
Cannot select a portal

### ISSUE THREAD

**Issue by Baron-Sengir** [YoFuzzy3/BungeePortals#14]
Hi! I recently installed bungeeportals on my server and am using them in my hub, I select a portal according to your spigot page (get WE wand, select with world edit wand, /bportals select water.  I am using a water portal) Aaaand I get: 0 blocks selected, 25 filitered. Use the selection in the create and remove commands.  I try again, same thing, I try and make the portal anyway, it doesn't work.  I have tried again and again, different places, different block filters, and nothing works.

**Comment by YoFuzzy3** [comment]
Probably something to do with the way water blocks work. This is not a plugin issue.
