### ISSUE TITLE
BungeePortal not working for 1.8 clients

### ISSUE THREAD

**Issue by PrimeRobotMC** [YoFuzzy3/BungeePortals#15]
Basically what the title says.
Players using the 1.7 is able to get teleported to the selected server via portals, so everything is completely normal to them, but players using 1.8 is different.
Same setup, same server, and same portals, however when they enter the portal, they do not get teleported to the server. This does NOT create any errors in the console, nor does that player get disconnected or anything like that. Its like the portal never existed.

Is this normal or is it just that BungeePortals only support 1.7 clients?

**Comment by YoFuzzy3** [comment]
Seems to work fine now.
