### ISSUE TITLE
Portal Visuals - Lava/Water/ etc

### ISSUE THREAD

**Issue by JhOnNeY** [YoFuzzy3/BungeePortals#25]
It would be pretty nice if (similar to multiverse-portals) we could put something in the middle of the portal to visually signify that a player needs to jump through to use the portal...

Thanks!

**Comment by GoadingGoat** [comment]
You already can put water or lava in the portal, or any other block that you can walk through. Easiest way is to set the block with worldedit, and use worldguard to stop lava/waterflow, and stop the player taking damage while in the portal.

**Comment by JhOnNeY** [comment]
Oh awesome I didn't even think about it that way

 Newbie minecraft player here ^_^. Thank you!!
